export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: ' places',
  },
  {
    id: 2,
    value: 'shell',
    label: ' Shell',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5⭐',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Grand Central Terminal',
    ditail: 'Grand Central Terminal in US (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 5×7 m²)',
    deliveryFee: "🛏️ 3 beds - 🚽 2 bothroom",
    category: 'place',
    cuisine: 'america',
    rating: 5,
    price: 2500,
    coverSrc: '/images/places/us9.jpg',
  },
  {
    id: 2,
    title: 'Bh1-Puram',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Near DTU Shahbhag Of Delhi - (✆ +91xxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 4,
    price: 1000,
    coverSrc: '/images/places/p1.webp',
  },
  {
    id: 3,
    title: 'Ming Li',
    ditail: 'Tinc Koy Park in China (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 4×7 m²)',
    deliveryFee: '🛏️ 2 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 3,
    price: 2000,
    coverSrc: '/images/places/ch4.jpg',
  },
  {
    id: 4,
    title: 'Lincoln ',
    ditail: 'Park Central Terminal in US (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 5×6 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'america',
    rating: 1,
    price: 1800,
    coverSrc: '/images/places/us11.jpg',
  },
  {
    id: 5,
    title: 'Tokni Tim',
    ditail: 'Prithviraj Road in Delhi (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 4.1×6 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 5,
    price: 6000,
    coverSrc: '/images/places/p2.webp',
  },
  {
    id: 6,
    title: 'Bh2 - minc lai',
    ditail: 'chi pic in China (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 7×8 m²)',
    deliveryFee: '🛏️ 4 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 5,
    price: 8000,
    coverSrc: '/images/places/ch5.jpg',
  },
  {
    id: 7,
    title: 'PDB M32',
    ditail: 'Lincoln Park in US (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 9×10 m²)',
    deliveryFee: '🛏️ 5 beds - 🚽 3 bothroom',
    category: 'place',
    cuisine: 'america',
    rating: 5,
    price: 9000,
    coverSrc: '/images/places/us12.jpg',
  },
  {
    id: 8,
    title: 'Pt Lok Seva',
    ditail: ' Jor Bagh in Delhi (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 3×4 m²)',
    deliveryFee: '🛏️ 1 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 1,
    price: 600,
    coverSrc: '/images/places/p7.jpg',
  },
  {
    id: 9,
    title: 'Ching T Kim',
    ditail: 'Jk Timmel (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 5×7 m²)',
    deliveryFee: '🛏️ 2 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 4,
    price: 2750,
    coverSrc: '/images/places/ch2.jpg',
  },
  {
    id: 10,
    title: 'Demek-lok',
    ditail: 'Lincoln Park in US (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 5×8 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'america',
    rating: 2,
    price: 4350,
    coverSrc: '/images/places/us13.jpg',
  },
  {
    id: 11,
    title: 'Bt Paas Bh1',
    ditail: 'Panchsheel Park in Delhi (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 4×7 m²)',
    deliveryFee: '🛏️ 2 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 3,
    price: 3300,
    coverSrc: '/images/places/p5.jpg',
  },
  {
    id: 12,
    title: 'Dim Sums',
    ditail: 'LT rought (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 4×5 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 2,
    price: 9000,
    coverSrc: '/images/places/ch1.jpg',
  },
  {
    id: 13,
    title: 'Mekel-kit',
    ditail: 'Lincoln Park in US (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 5×8 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'america',
    rating: 2,
    price: 4350,
    coverSrc: '/images/places/us15.jpg',
  },
  {
    id: 14,
    title: 'Jival BT',
    ditail: 'Panchsheel Park in Delhi (✆ +xxxxxxxxx)',
    serviceTime: '(🏠 4×7 m²)',
    deliveryFee: '🛏️ 2 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 3,
    price: 3300,
    coverSrc: '/images/places/p10.jpg',
  },
  {
    id: 15,
    title: 'Bh1 xykg',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Near DTU Shahbhag Of Delhi - (✆ +91xxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 4,
    price: 2500,
    coverSrc: '/images/places/us11.jpg',
  },
  {
    id: 16,
    title: 'Bh2 kmk',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Near DTU Shahbhag Of Delhi - (✆ +91xxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 4,
    price: 1500,
    coverSrc: '/images/places/ind5.webp',
  },
  {
    id: 17,
    title: 'HK Bh2 ghgf',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Dhcu li pi in china - (✆ +xxxxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 4,
    price: 1500,
    coverSrc: '/images/places/us18.webp',
  },
  {
    id: 18,
    title: 'HMM BH2 xykg',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'litt Shah Of Delhi - (✆ +91xxxxxxxx)',
    deliveryFee: '🛏️ 5 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 3,
    price: 6500,
    coverSrc: '/images/places/ind3.webp',
  },
  {
    id: 19,
    title: 'Gb road bh2',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Muyk bhag Of Delhi - (✆ +91xxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'india',
    rating: 2,
    price: 2900,
    coverSrc: '/images/places/ind4.webp',
  },
  {
    id: 20,
    title: 'Ktd-road',
    ditail: 'NT bhag in US',
    serviceTime: '(🏠 5×8 m²)',
    deliveryFee: '🛏️ 3 beds - 🚽 2 bothroom',
    category: 'place',
    cuisine: 'america',
    rating: 3,
    price: 4350,
    coverSrc: '/images/places/us18.webp',
  },
  {
    id: 21,
    title: 'Onki lik Tii',
    serviceTime: '(🏠 4×6 m²)',
    ditail: 'Dhcu li pi in china - (✆ +xxxxxxxxxx)',
    deliveryFee: '🛏️ 3 beds - 🚽 1 bothroom',
    category: 'place',
    cuisine: 'china',
    rating: 4,
    price: 1500,
    coverSrc: '/images/places/ch15.jpg',
  }

  
];
